<?php $this->layout('Layout/layout') ?>

<div class="list-group">
    <a class="list-group-item" href="/view">/view</a>
    <a class="list-group-item" href="/relative">/relative</a>
    <a class="list-group-item" href="/user/hoge">/user/hoge</a>
    <a class="list-group-item" href="/response">/response</a>
    <a class="list-group-item" href="/error/403">/error/403</a>
    <a class="list-group-item" href="/raise">/raise</a>
</div>
