<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <script src="//code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
</head>
<body id="body">
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Example</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="/view">/view</a></li>
                <li><a href="/user/hoge">/user/hoge</a></li>
                <li><a href="/response">/response</a></li>
                <li><a href="/raise">/raise</a></li>

            </ul>
            <form class="navbar-form navbar-right" action="/logout">
                <button type="submit" class="btn btn-default">Logout</button>
            </form>
            <div class="navbar-text navbar-right">
                <?= $this->h($identify['username']) ?>
            </div>
        </div>
    </div>
</nav>
<div class="container">
    <?= $content ?>
</div>
</body>
</html>
